<a href="https://colab.research.google.com/github/parthnijh/intro-to-pytorch/blob/main/Introduction_to_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt

# Intro to tensors

## creating  a tensor


In [3]:
# scalar

scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.item() ## get tensor back as python int

7

In [5]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [10]:
## matrix
matrix =torch.tensor([[1,2],[3,4]])
matrix.ndim
matrix.shape

torch.Size([2, 2])

In [11]:
TENSOR=torch.tensor([[[1,2,3],[3,6,9],[10,5,4]]])

In [12]:
TENSOR.ndim
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0][0]

tensor([1, 2, 3])

# Random Tensors

In [18]:
random_tensors=torch.rand(3,4)
random_tensors

tensor([[0.7753, 0.0508, 0.8960, 0.3486],
        [0.9493, 0.4269, 0.0336, 0.7926],
        [0.5409, 0.1176, 0.7844, 0.7983]])

In [19]:
# Create a random tensor with similar shape to an image tensor
random_tensors=torch.rand(224,224,3)
random_tensors

tensor([[[0.5268, 0.5508, 0.0264],
         [0.9210, 0.5894, 0.3099],
         [0.6134, 0.7858, 0.2977],
         ...,
         [0.1174, 0.2356, 0.6096],
         [0.8248, 0.1585, 0.6733],
         [0.8157, 0.3168, 0.3795]],

        [[0.4275, 0.2032, 0.4500],
         [0.9524, 0.1052, 0.5551],
         [0.2493, 0.1391, 0.2613],
         ...,
         [0.8740, 0.0334, 0.2261],
         [0.2816, 0.4733, 0.2344],
         [0.6940, 0.9386, 0.6840]],

        [[0.2477, 0.5961, 0.4777],
         [0.6159, 0.5839, 0.1024],
         [0.2352, 0.8450, 0.2853],
         ...,
         [0.4040, 0.8369, 0.6517],
         [0.6578, 0.6223, 0.9235],
         [0.2670, 0.0471, 0.4858]],

        ...,

        [[0.4879, 0.1727, 0.4240],
         [0.1321, 0.3417, 0.2628],
         [0.3890, 0.2223, 0.6908],
         ...,
         [0.5073, 0.0817, 0.3514],
         [0.3382, 0.4953, 0.6080],
         [0.5761, 0.4761, 0.8604]],

        [[0.4346, 0.4098, 0.3847],
         [0.6519, 0.7676, 0.1196],
         [0.

# Create a tensor of zeroes

In [20]:
zeroes=torch.zeros(3,4)
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Create A range of tensors

In [24]:
t=torch.arange(1,11,2)
t

tensor([1, 3, 5, 7, 9])

In [26]:
torchzeros=torch.zeros_like(t)
torchzeros

tensor([0, 0, 0, 0, 0])

# tensor datatypes

Tensor datatypes
There are many different tensor datatypes available in PyTorch.

Some are specific for CPU and some are better for GPU.

Getting to know which one can take some time.

Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is torch.float32 or torch.float.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

Note: An integer is a flat round number like 7 whereas a float has a decimal 7.0.

The reason for all of these is to do with precision in computing.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

Resources:

See the PyTorch documentation for a list of all available tensor datatypes.
Read the Wikipedia page for an overview of what precision in computing) is.
Let's see how to create some tensors with specific datatypes. We can do so using the dtype parameter

In [27]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [29]:
float16=float_32_tensor.type(torch.float16)
float16

tensor([3., 6., 9.], dtype=torch.float16)