<a href="https://colab.research.google.com/github/parthnijh/intro-to-pytorch/blob/main/Pytorch_NN_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()## parent class constructor
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear(features)#calc z=wx+b
    out=self.sigmoid(out)#pass through sigmoid
    return out

In [2]:
features=torch.rand(10,5)
model=Model(features.shape[1])
model(features)

tensor([[0.4013],
        [0.4607],
        [0.4013],
        [0.4701],
        [0.4505],
        [0.4345],
        [0.4818],
        [0.4170],
        [0.4104],
        [0.3468]], grad_fn=<SigmoidBackward0>)

In [3]:
#show model weights
model.linear.weight,model.linear.bias

(Parameter containing:
 tensor([[-0.0738,  0.0241, -0.4313, -0.1529, -0.1955]], requires_grad=True),
 Parameter containing:
 tensor([0.1483], requires_grad=True))

In [4]:
pip install torchinfo

In [5]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [6]:
import torch
import torch.nn as nn
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()## parent class constructor

    self.linear1=nn.Linear(num_features,3)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear1(features)#calc z=wx+b
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)#pass through sigmoid
    return out

In [7]:
features=torch.rand(10,5)
model=Model(features.shape[1])
model(features)

tensor([[0.6309],
        [0.6062],
        [0.5858],
        [0.6292],
        [0.6167],
        [0.6046],
        [0.6255],
        [0.6232],
        [0.6269],
        [0.5985]], grad_fn=<SigmoidBackward0>)

In [8]:
import torch
import torch.nn as nn
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()## parent class constructor
    self.network=nn.Sequential(
         nn.Linear(num_features,3),
         nn.ReLU(),
         nn.Linear(3,1),
         nn.Sigmoid()

    )




  def forward(self,features):
    out=self.network(features)

    return out