<a href="https://colab.research.google.com/github/parthnijh/intro-to-pytorch/blob/main/Pytorch_NN_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()## parent class constructor
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear(features)#calc z=wx+b
    out=self.sigmoid(out)#pass through sigmoid
    return out

In [3]:
features=torch.rand(10,5)
model=Model(features.shape[1])
model(features)

tensor([[0.3981],
        [0.4387],
        [0.4249],
        [0.3938],
        [0.4159],
        [0.4010],
        [0.4007],
        [0.3693],
        [0.4273],
        [0.4624]], grad_fn=<SigmoidBackward0>)

In [4]:
#show model weights
model.linear.weight,model.linear.bias

(Parameter containing:
 tensor([[ 0.0656, -0.0586, -0.1282, -0.4227,  0.0569]], requires_grad=True),
 Parameter containing:
 tensor([-0.0808], requires_grad=True))

In [6]:
pip install torchinfo

In [7]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [8]:
import torch
import torch.nn as nn
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()## parent class constructor
    self.linear1=nn.Linear(num_features,3)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear1(features)#calc z=wx+b
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)#pass through sigmoid
    return out

In [9]:
features=torch.rand(10,5)
model=Model(features.shape[1])
model(features)

tensor([[0.3703],
        [0.3817],
        [0.3859],
        [0.3816],
        [0.3682],
        [0.3459],
        [0.3724],
        [0.3545],
        [0.3644],
        [0.3554]], grad_fn=<SigmoidBackward0>)